# Generated by Django 4.2.1 on 2023-05-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.TextField(max_length=128)),
                ('age', models.TextField()),
                ('average_mark', models.TextField()),
            ],
        ),
    ]
